# Generated by Django 5.1.1 on 2024-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameStints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.CharField(max_length=10)),
                ('stintStart', models.CharField(max_length=10)),
                ('stintEnd', models.CharField(max_length=10)),
                ('awayPos', models.IntegerField()),
                ('homePos', models.IntegerField()),
                ('awayScore', models.IntegerField()),
                ('homeScore', models.IntegerField()),
            ],
        ),
    ]
