# Generated by Django 5.1.1 on 2025-05-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_brand_carmodel_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='gps_tracker_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
