# Generated by Django 5.1.1 on 2025-05-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_fleet_gps_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='gps_tracker_id',
            field=models.IntegerField(),
        ),
    ]
