# Generated by Django 5.1.1 on 2025-04-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_brand_carmodel_fleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_report_id', models.IntegerField()),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('in_process', 'In process'), ('done', 'Done'), ('fail', 'Fail')], max_length=20)),
                ('server_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GpsTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GpsTripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_report_id', models.IntegerField()),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('server_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GpsZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('navixy_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GpsTripReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('length', models.FloatField()),
                ('time_sec', models.FloatField()),
                ('time_string', models.CharField(max_length=50)),
                ('avg_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('idle_sec', models.FloatField()),
                ('idle_string', models.CharField(max_length=50)),
                ('time_hour', models.FloatField()),
                ('idle_hour', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='navixy.gpstripreport')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.fleet')),
                ('from_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_lines', to='navixy.gpszone')),
                ('to_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_lines', to='navixy.gpszone')),
            ],
        ),
    ]
