# Generated by Django 5.1.1 on 2025-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpstripreportline',
            name='from_loc_char',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gpstripreportline',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpstripreportline',
            name='to_loc_char',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gpstripreportline',
            name='to_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
