# Generated by Django 5.1.1 on 2025-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0002_gpstripreportline_from_loc_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsreport',
            name='report_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('stop', 'Stop'), ('fuel', 'Fuel'), ('motohour', 'Moto Hour'), ('zone', 'Zone')], default='trip', max_length=20),
        ),
    ]
