# Generated by Django 5.1.1 on 2025-05-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0003_gpsreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstripreportline',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='navixy.gpsreport'),
        ),
    ]
