# Generated by Django 5.1.1 on 2025-05-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0005_alter_gpstripreportline_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpszone',
            name='navixy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
