# Generated by Django 5.1.1 on 2025-05-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0006_alter_gpszone_navixy_id'),
        ('pages', '0006_alter_fleet_gps_tracker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsFuelFillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_datetime', models.DateTimeField()),
                ('volume', models.FloatField()),
                ('start_vol', models.FloatField()),
                ('end_vol', models.FloatField()),
                ('type', models.CharField(choices=[('fill', 'Fill'), ('drain', 'Drain')], max_length=10)),
                ('mileage', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navixy.gpszone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_fill_lines', to='navixy.gpsreport')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='GpsFuelReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('mileage', models.FloatField()),
                ('start_bal', models.FloatField()),
                ('end_bal', models.FloatField()),
                ('consumed', models.FloatField()),
                ('consumpt_per_dist', models.FloatField()),
                ('fillings_count', models.IntegerField()),
                ('fillings_volume', models.FloatField()),
                ('drains_count', models.IntegerField()),
                ('drains_volume', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_detailed_lines', to='navixy.gpsreport')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='GpsMotohourReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('ownership_type', models.CharField(blank=True, choices=[('own', 'Own'), ('leasing', 'Leasing'), ('partner', 'Partner'), ('rental', 'Rental')], max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('in_movement_sec', models.FloatField()),
                ('in_movement_hour', models.FloatField()),
                ('duration_sec', models.FloatField()),
                ('duration_hour', models.FloatField()),
                ('end_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='end_motohours', to='navixy.gpszone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motohour_lines', to='navixy.gpsreport')),
                ('start_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='start_motohours', to='navixy.gpszone')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='GpsStopReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('loc_char', models.CharField(blank=True, max_length=255)),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('to_time', models.DateTimeField(blank=True, null=True)),
                ('idle_sec', models.FloatField()),
                ('idle_hour', models.FloatField()),
                ('idle_string', models.CharField(max_length=100)),
                ('ignition_sec', models.FloatField()),
                ('ignition_string', models.CharField(max_length=100)),
                ('ignition_hour', models.FloatField()),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stop_location', to='navixy.gpszone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_lines', to='navixy.gpsreport')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='GpsZoneReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField()),
                ('roster_date', models.DateField(blank=True, null=True)),
                ('in_datetime', models.DateTimeField(blank=True, null=True)),
                ('out_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.FloatField()),
                ('duration_string', models.CharField(max_length=100)),
                ('duration_hour', models.FloatField()),
                ('in_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zone_in_location', to='navixy.gpszone')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zone_location', to='navixy.gpszone')),
                ('out_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zone_out_location', to='navixy.gpszone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_lines', to='navixy.gpsreport')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.fleet')),
            ],
        ),
        migrations.DeleteModel(
            name='GpsTripReport',
        ),
    ]
