# Generated by Django 5.1.1 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0007_gpsfuelfillreport_gpsfuelreportline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpszone',
            name='english_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
