# Generated by Django 5.1.1 on 2025-05-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0008_gpszone_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsfuelfillreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpsmotohourreportline',
            name='end_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_motohours', to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpsmotohourreportline',
            name='start_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_motohours', to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpsstopreportline',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_location', to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpszonereportline',
            name='in_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_in_location', to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpszonereportline',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_location', to='navixy.gpszone'),
        ),
        migrations.AlterField(
            model_name='gpszonereportline',
            name='out_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_out_location', to='navixy.gpszone'),
        ),
    ]
