# Generated by Django 5.1.1 on 2025-05-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0009_alter_gpsfuelfillreport_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('tracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='navixy.gpstracker')),
            ],
        ),
    ]
