# Generated by Django 5.1.1 on 2025-05-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navixy', '0010_trackpoint'),
        ('pages', '0006_alter_fleet_gps_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.fleet'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='tracker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_points', to='navixy.gpstracker'),
        ),
    ]
